# --- START OF FILE nodes/decision.py ---
from models.state import InterviewState
# LLM utils might not be needed here anymore if only using scores for decision
# from utils.llm import get_openrouter_completion, format_messages_for_openrouter
import json
from typing import Dict, List, Any
import traceback # Keep for general error handling if any other part fails

# Node returns dict containing hiring_recommendation and the final message
def hiring_decision_node(state: InterviewState) -> Dict[str, Any]:
    """
    Generate hiring recommendation based on SCORE THRESHOLDS using average scores
    from answer analyses, and includes the final message.
    Returns dict with 'hiring_recommendation' and 'messages'.
    """
    print("--- Executing Node: hiring_decision_node ---")
    print("--- Using Threshold-Based Decision Logic ---") # Log the change

    # --- Prerequisite Check ---
    # We still need the feedback text generated by the previous node to display it.
    if not state.feedback:
        print("hiring_decision_node: Feedback text missing from state.")
        recommendation_str = "Neutral: Incomplete data for final summary."
        # Even if recommendation fails, send a concluding message
        final_message_content = "Interview complete. Final summary could not be fully generated due to missing data."
        final_message = {"role": "assistant", "content": final_message_content}
        # Return both the default recommendation and the concluding message
        return {"hiring_recommendation": recommendation_str, "messages": [final_message]}

    # --- 1. Calculate Average Scores ---
    scores = {"relevance": 0, "technical": 0, "communication": 0, "overall": 0}
    count = len(state.answer_analyses)
    recommendation_str = "" # Initialize recommendation string

    if state.answer_analyses and count > 0:
        # Calculate sums
        for analysis in state.answer_analyses:
            scores["relevance"] += analysis.get("relevance_score", 0) # Default to 0 if key missing
            scores["technical"] += analysis.get("technical_accuracy", 0)
            scores["communication"] += analysis.get("communication_score", 0)
            scores["overall"] += analysis.get("overall_score", 0)
        # Calculate averages and round
        for key in scores:
            scores[key] = round(scores[key] / count, 1)
        print(f"hiring_decision_node: Calculated Average Scores: {scores}")

        # --- 2. Define Thresholds (Example using 'overall' score) ---
        # These values are examples and should be tuned based on desired criteria
        STRONG_RECOMMEND_THRESHOLD = 8.0
        RECOMMEND_THRESHOLD = 6.5
        NEUTRAL_THRESHOLD = 5.0

        recommendation_category = "Neutral" # Default category
        explanation = "Performance showed a mix of strengths and areas needing improvement." # Default explanation

        # --- 3. Apply Threshold Rules ---
        overall_score = scores.get("overall", 0) # Get the calculated overall score safely

        if overall_score >= STRONG_RECOMMEND_THRESHOLD:
            recommendation_category = "Strong Recommend"
            explanation = f"Candidate consistently excelled across multiple areas, demonstrating strong technical ability and clear communication (Average Overall Score: {overall_score})."
        elif overall_score >= RECOMMEND_THRESHOLD:
            recommendation_category = "Recommend"
            explanation = f"Candidate performed well, meeting the core requirements of the role effectively (Average Overall Score: {overall_score})."
        elif overall_score >= NEUTRAL_THRESHOLD:
            recommendation_category = "Neutral"
            explanation = f"Candidate met some requirements but showed notable areas needing development or lacked consistency (Average Overall Score: {overall_score})."
        else: # overall_score < NEUTRAL_THRESHOLD
            recommendation_category = "Do Not Recommend"
            explanation = f"Candidate did not consistently demonstrate the necessary skills or required level of understanding for the role (Average Overall Score: {overall_score})."

        # --- 4. Format Final Recommendation String ---
        recommendation_str = f"{recommendation_category}: {explanation}"

    else:
        # Handle case where no analyses were available for scoring
        print("hiring_decision_node: No answer analyses found for scoring. Defaulting recommendation.")
        recommendation_str = "Neutral: Insufficient analysis data for a score-based recommendation."
        # The feedback text itself might still be useful

    # --- 5. Construct Final Message ---
    # Include the feedback generated by the previous node and the rule-based recommendation
    final_message_content = (
        f"Thank you for completing the interview. Here's your feedback:\n\n"
        f"{state.feedback}\n\n" # Feedback text from summarize_feedback_node
        f"Hiring Recommendation: {recommendation_str}\n\n" # Rule-based recommendation
        f"This has been an automated interview simulation. Thank you for participating!"
    )
    final_message = {"role": "assistant", "content": final_message_content}

    print(f"hiring_decision_node: Recommendation (Threshold-based): {recommendation_str}")

    # --- 6. Return Updates ---
    # Return the recommendation string (for state) and the final message (for add_messages)
    return {
        "hiring_recommendation": recommendation_str,
        "messages": [final_message]
    }
# --- END OF FILE nodes/decision.py ---