# --- START OF FILE nodes/feedback.py ---
from models.state import InterviewState
from utils.llm import get_openrouter_completion, format_messages_for_openrouter
import json
from typing import Dict, Any # Add Dict, Any
import traceback

# Node returns dict of updates for non-message fields
def summarize_feedback_node(state: InterviewState) -> Dict[str, Any]:
    """
    Generate a comprehensive feedback summary based on all answers.
    Returns dict containing 'feedback'.
    """
    print("--- Executing Node: summarize_feedback_node ---")

    # Check if prerequisite data is available
    if not state.interview_complete or not state.answer_analyses or not state.interview_questions:
        print("summarize_feedback_node: Prerequisite data missing (complete flag, analyses, or questions).")
        # Return a fallback feedback message if possible, or empty dict
        return {"feedback": "Unable to generate feedback due to missing interview data."}

    # Prepare data for feedback generation
    questions_and_answers = []
    # Ensure lists have compatible lengths
    num_items = min(len(state.interview_questions), len(state.answers), len(state.answer_analyses))
    for i in range(num_items):
        qa_pair = {
            "question": state.interview_questions[i],
            "answer": state.answers[i],
            "analysis": state.answer_analyses[i]
        }
        questions_and_answers.append(qa_pair)

    if not questions_and_answers:
         return {"feedback": "No question/answer pairs found to generate feedback from."}

    system_prompt = """
    You are an expert technical interviewer providing feedback to a job candidate.
    Based on the candidate's answers and their analyses, provide comprehensive feedback.
    Include: Overall impression, Key strengths, Areas for improvement, Specific examples, Actionable advice.
    Be constructive, specific, and balanced. Aim to help the candidate improve.
    Structure your response as a well-formatted feedback summary.
    """

    qa_text = ""
    for i, qa in enumerate(questions_and_answers):
        qa_text += f"Question {i+1}: {qa['question']}\n"
        qa_text += f"Answer: {qa['answer']}\n"
        qa_text += f"Analysis: {json.dumps(qa['analysis'], indent=2)}\n\n"

    messages = format_messages_for_openrouter(
        system_message=system_prompt,
        messages=[{
            "role": "user",
            "content": f"Candidate: {state.candidate_name}\nBackground: {state.candidate_background}\n\nInterview Q&A and Analyses:\n\n{qa_text}\nPlease provide comprehensive feedback."
        }]
    )

    feedback_str = ""
    try:
        feedback_str = get_openrouter_completion(messages, max_tokens=1500)
        print("summarize_feedback_node: Feedback generated by LLM.")
    except Exception as e:
        print(f"summarize_feedback_node: Error calling LLM for feedback: {e}")
        traceback.print_exc()
        feedback_str = "Unable to generate detailed feedback via LLM at this time. Please review individual analyses."

    # Return ONLY the updated non-message field
    return {"feedback": feedback_str.strip()}

# --- END OF FILE nodes/feedback.py ---